# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER_GREEN,ROLE_USER_YELLOW,ROLE_USER_RED,ROLE_USER_BLUE
        ROLE_USER_GREEN : ROLE_USER
        ROLE_USER_YELLOW : ROLE_USER
        ROLE_USER_RED : ROLE_USER
        ROLE_USER_BLUE : ROLE_USER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: 
                users:
                    camel:
                        password: qais
                        roles: 'ROLE_USER'
                    Mred:
                        password: red
                        roles: 'ROLE_USER_RED'
                    Mblue:
                        password: blue
                        roles: 'ROLE_USER_BLUE'
                    Mgreen:
                        password: green
                        roles: 'ROLE_USER_GREEN'
                    Myellow:
                        password: yellow
                        roles: 'ROLE_USER_YELLOW'
                    
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

        
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            #http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                check_path: /loginCheck
                login_path: /login

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
            logout:
                path: /logout
                target: /
    access_control:
        # require ROLE_ADMIN for /admin
        - { path: ^/admin , roles: ROLE_ADMIN }
        - { path: ^/red , roles: ROLE_USER_RED }
        - { path: ^/blue , roles: ROLE_USER_BLUE }
        - { path: ^/green , roles: ROLE_USER_GREEN }
        - { path: ^/yellow , roles: ROLE_USER_YELLOW }
        
    